import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import "./main.css"
import React from "react"
import Navbar from "@/app/_menu/Navbar"
import MainContentWrapper from "./MainContentWrapper";
import Footer from "./_footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiasing`}>
        <header className="z-30">
          <Navbar />
        </header>
        <MainContentWrapper>
          {children}
        </MainContentWrapper>
        <Footer />
      </body>
    </html>
  );
}
